name: Test Inputs
on:
  workflow_dispatch:
    inputs:
      release_version:
        description: Release version (e.g. 0.1.0)
        required: true
        type: string
        default: 0.1.0
      create_release:
        description: Push to GitHub Releases
        required: true
        type: boolean
        default: false
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo ok
